# Generated by Django 2.2.6 on 2019-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191226_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_domain',
            field=models.CharField(max_length=255),
        ),
    ]
