# Generated by Django 2.2.7 on 2019-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
