# Generated by Django 2.2.7 on 2019-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20191202_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='title',
            field=models.TextField(default='Building title', max_length=200),
        ),
    ]
