# Generated by Django 2.2.7 on 2019-12-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='floor',
            new_name='floor_count',
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(default='Floor number', max_length=200)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
        ),
    ]
