# Generated by Django 2.2.7 on 2019-12-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20191211_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Floor'),
        ),
    ]
