# Generated by Django 2.2.7 on 2019-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_room_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.TextField(default='Number', max_length=100),
        ),
    ]
