# Generated by Django 2.2.7 on 2019-12-16 14:24

import buildings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_auto_20191213_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Number', max_length=30),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
