# Generated by Django 2.2.7 on 2019-12-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_auto_20191216_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='building',
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Building'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floor_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Floor'),
        ),
    ]
