# Generated by Django 2.2.7 on 2019-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_auto_20191216_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='size',
        ),
        migrations.AlterField(
            model_name='building',
            name='floor_count',
            field=models.PositiveIntegerField(null=True, verbose_name='Floors number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(default='Building title', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(null=True, verbose_name='Floor number'),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
