# Generated by Django 2.2.7 on 2019-12-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
