# Generated by Django 2.2.7 on 2019-12-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_auto_20191225_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Free', 'Free')], default='', max_length=30),
        ),
    ]
