# Generated by Django 2.2.6 on 2020-01-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('buildings', '0014_interval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='user',
        ),
        migrations.AddField(
            model_name='building',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='room',
            name='beamer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(null=True, verbose_name='Capacity'),
        ),
    ]
