# Generated by Django 2.2.6 on 2020-01-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_auto_20200104_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='room',
        ),
        migrations.AlterField(
            model_name='interval',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Free', 'Free')], default='Free', max_length=30),
        ),
    ]
