# Generated by Django 2.2.6 on 2020-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_auto_20200104_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.ManyToManyField(blank=True, to='buildings.RoomFeature'),
        ),
    ]
