# Generated by Django 2.2.6 on 2019-12-09 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ('created',),
            },
        ),
    ]
