# Generated by Django 2.2.6 on 2019-12-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='', max_length=30),
        ),
    ]
