# Generated by Django 2.2.6 on 2019-12-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20191209_1321'),
        ('bookings', '0002_auto_20191209_1254'),
    ]

    operations = [
    ]
