# Generated by Django 2.2.6 on 2019-12-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_interval_status'),
        ('bookings', '0003_merge_20191216_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Interval'),
        ),
    ]
