# Generated by Django 2.2.6 on 2019-12-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Interval'),
        ),
    ]
