# Generated by Django 2.2.6 on 2020-01-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20200102_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
