# Generated by Django 2.2.6 on 2020-01-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
    ]
