# Generated by Django 2.2.6 on 2020-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20200123_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
