# Generated by Django 2.2.6 on 2020-01-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
